version: "3"

dotenv:
    - .env
    - "{{.ENV}}/.env."
    - "{{.HOME}}/.env"

vars:
    LOG_LEVEL: INFO

env:
    REDPANDA_VERSION: latest
    REDPANDA_CONSOLE_VERSION: latest
    GRAFANA_VERSION: latest
    PROMETHEUS_VERSION: latest
    ALERT_MANAGER_VERSION: latest
    MAILPIT_VERSION: latest
    LOCALSTACK_VERSION: latest
    AWS_CLI_VERSION: latest
    SCHEMA_REGISTRY_URL: http://localhost:18081
    REDPANDA_SEED_URL: localhost:19092
    AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
    AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    AWS_REGION: us-east-1

tasks:
    check:
        cmds:
            - trunk check -a

    clean:
        cmds:
            - task: demo-stop
            - rm -f docker/mailpit/data/mailpit.*

    demo-start:
        cmds:
            - task: docker-up
            - sleep 10
            - rpk profile create demo --from-profile rpk-docker-profile.yml
            - rpk profile use demo
            # - rpk registry schema create demo-value --schema schemas/demo.avsc
            - rpk topic create __redpanda.connect.logs demo
            - echo "Grafana running on http://localhost:3000"
            - echo "Redpanda console running on http://localhost:8080"
            - echo "Mailpit running on http://localhost:8025"
            - echo "Prometheus running on http://localhost:9090"
            - echo "Alertmanager running on http://localhost:9093"
            - echo "Localstack running on http://localhost:4566"

    docker-up:
        cmds:
            - docker-compose up -d --wait-timeout 60

    demo-stop:
        cmds:
            - docker-compose down -v --remove-orphans
            - rm -rf docker/localstack/*
            - rpk profile delete demo

    demo-cp:
        cmds:
            - aws --endpoint-url=http://localhost:4566 s3 cp data/demo.csv s3://demobucket/

    demo-connect:
        cmds:
            - docker run --rm -v $PWD/config:/config -p 4195:4195 docker.redpanda.com/redpandadata/redpanda connect run /config/connect.yaml