version: "3"

dotenv:
  - .env
  - "{{.ENV}}/.env."
  - "{{.HOME}}/.env"

vars:
  LOG_LEVEL: INFO

tasks:
  check:
    cmds:
      - trunk check -a

  clean:
    cmds:
      - task: demo-stop

  demo-start:
    cmds:
      - docker-compose up -d --wait-timeout 60
      - sleep 30
      - rpk profile create demo --from-profile rpk-docker-profile.yml
      - rpk profile use demo
      - rpk registry schema create demo-value --schema schemas/demo.avsc
      - rpk topic create demo demo-dlq
      - echo "Redpanda console running on http://localhost:8080"
      - echo "Localstack running on http://localhost:4566"

  demo-stop:
    cmds:
      - docker-compose down -v --remove-orphans
      - rm -rf docker/localstack/*
      - rpk profile delete demo

  demo-cp:
    cmds:
      - aws --endpoint-url=http://localhost:4566 s3 cp data/demo.csv s3://demobucket/
      - aws --endpoint-url=http://localhost:4566 s3 cp data/demo-bad.csv s3://demobucket/

  logs:
    cmds:
      - docker logs connect -f
