http:
  enabled: false
  address: 0.0.0.0:4195
  root_path: /benthos
  debug_endpoints: false
  cert_file: ""
  key_file: ""
  cors:
    enabled: false
    allowed_origins: []
  basic_auth:
    enabled: false
    realm: restricted
    username: ""
    password_hash: ""
    algorithm: sha256
    salt: ""
input:
  label: "localstack"
  aws_s3:
    bucket: "demobucket"
    region: us-east-1
    endpoint: http://localstack:4566
    credentials:
      id: AKIAIOSFODNN7EXAMPLE
      secret: wJalrXUtnFEMIK7MDENGbPxRfiCYEXAMPLEKEY
    force_path_style_urls: true
    delete_objects: false
    scanner:
      to_the_end: {}
    sqs:
      url: "http://localstack:4566/000000000000/demoqueue"
      key_path: Records.*.s3.object.key
      bucket_path: Records.*.s3.bucket.name
      max_messages: 10
buffer:
  none: {}
pipeline:
  threads: -1
  processors: []
output:
  stdout: {}
input_resources: []
processor_resources: []
output_resources: []
cache_resources: []
rate_limit_resources: []
logger:
  level: INFO
  format: logfmt
  add_timestamp: false
  level_name: level
  timestamp_name: time
  message_name: msg
  static_fields:
    '@service': benthos
  file:
    path: ""
    rotate: false
    rotate_max_age_days: 0
metrics:
  prometheus: {}
  mapping: ""
tracer:
  none: {}
shutdown_delay: 0s
shutdown_timeout: 20s
tests: []
redpanda:
  seed_brokers: []
  logs_topic: __redpanda.connect.logs
  logs_level: info
  client_id: benthos
  rack_id: ""
  timeout: 10s
  max_message_bytes: 1MB
  tls:
    enabled: false
    skip_cert_verify: false
    enable_renegotiation: false
    root_cas: ""
    root_cas_file: ""
    client_certs: []
  sasl: []

